# Generated by Django 5.1.6 on 2025-03-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0002_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
