# Generated by Django 5.1.6 on 2025-03-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0003_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='users',
            name='useremail',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
